/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Bloc_nota_Controlador;

/**
 *
 * @author Osmar
 */
public final class Bloc_Notas extends javax.swing.JInternalFrame {
    Bloc_nota_Controlador bc;
    /**
     * Creates new form Bloc_Notas
     */
    public Bloc_Notas() {
        initComponents();
        iniciar_controlador();
    }
   
    public void  iniciar_controlador(){
       bc = new Bloc_nota_Controlador (this);
       this.abrirFileButton.addActionListener(bc);
       this.guardarFileButton.addActionListener(bc);
    }
      public void showText(String abrirFile) {
        this.editorPane1.setText(abrirFile);
    }
      
   public String  getText() {
       return this.editorPane1.getText();
    } 
    
    
    
    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuToolBar = new javax.swing.JToolBar();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        abrirarchivoLabel = new javax.swing.JLabel();
        abrirFileButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        guardariconLabel2 = new javax.swing.JLabel();
        guardarFileButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPane1 = new javax.swing.JEditorPane();

        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.lightGray);
        setToolTipText(abrirFileButton.getToolTipText());
        setFrameIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\notepad.png")); // NOI18N

        MenuToolBar.setRollover(true);
        MenuToolBar.add(jSeparator2);

        abrirarchivoLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\abrir-documento.png")); // NOI18N
        MenuToolBar.add(abrirarchivoLabel);

        abrirFileButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        abrirFileButton.setText(" Abrir ");
        abrirFileButton.setActionCommand("abrirFile");
        abrirFileButton.setBorder(null);
        abrirFileButton.setFocusable(false);
        abrirFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrirFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(abrirFileButton);
        MenuToolBar.add(jSeparator1);

        guardariconLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\guardar-el-archivo.png")); // NOI18N
        MenuToolBar.add(guardariconLabel2);

        guardarFileButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        guardarFileButton.setText("Guardar");
        guardarFileButton.setActionCommand("guardarFile");
        guardarFileButton.setBorder(null);
        guardarFileButton.setFocusable(false);
        guardarFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarFileButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MenuToolBar.add(guardarFileButton);

        jScrollPane1.setViewportView(editorPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuToolBar, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuToolBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar MenuToolBar;
    private javax.swing.JButton abrirFileButton;
    private javax.swing.JLabel abrirarchivoLabel;
    private javax.swing.JEditorPane editorPane1;
    private javax.swing.JButton guardarFileButton;
    private javax.swing.JLabel guardariconLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables


   

    

  
   
}
