/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador_main;

/**
 *
 * @author osmar
 */
public final class VentanaPrincipal extends javax.swing.JFrame {
      Controlador_main cm;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        Inicio();
    }
    
   public void Inicio(){
    cm = new  Controlador_main(this);
    blocMenuItem.addActionListener(cm);
   this.blocMenuItem.addActionListener(cm);
   salirMenuItem.addActionListener(cm);
   
    }    

   public void showChild(Bloc_Notas bc, boolean b) {
         Desktop.add(bc);
           bc.setVisible(true);
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ArchivoMenu = new javax.swing.JMenu();
        blocMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        salirMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        ArchivoMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\windows.png")); // NOI18N
        ArchivoMenu.setText("Opciones");
        ArchivoMenu.setToolTipText("");
        ArchivoMenu.setActionCommand("archivo");

        blocMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\notas.png")); // NOI18N
        blocMenuItem.setText("Bloc de notas");
        blocMenuItem.setActionCommand("bloc");
        ArchivoMenu.add(blocMenuItem);
        ArchivoMenu.add(jSeparator2);

        salirMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\acer\\Documents\\NetBeansProjects\\Tarea\\src\\main\\Recursos\\images\\cerrar-sesion.png")); // NOI18N
        salirMenuItem.setText("Salir");
        salirMenuItem.setActionCommand("salir");
        ArchivoMenu.add(salirMenuItem);

        jMenuBar1.add(ArchivoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArchivoMenu;
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem blocMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem salirMenuItem;
    // End of variables declaration//GEN-END:variables

 

  


}
